CREATE OR REPLACE PACKAGE ACCESS_UTILS
IS
  FUNCTION LOG_IN
    (
      PASSWD_IN   IN VARCHAR2,
      USERNAME_IN IN VARCHAR2
    )
    RETURN INTEGER;
    
  FUNCTION INREGISTRARE
    (
      PASSWD_IN   IN VARCHAR2,
      USERNAME_IN IN VARCHAR2,
      EMAIL_IN    IN VARCHAR2
    )
    RETURN INTEGER;
END ACCESS_UTILS;
/
CREATE OR REPLACE PACKAGE BODY ACCESS_UTILS
IS
    FUNCTION LOG_IN
    (
      PASSWD_IN   IN VARCHAR2,
      USERNAME_IN IN VARCHAR2
    )
    RETURN INTEGER
  IS
    VID_PROFILE INTEGER;
  BEGIN
    SELECT ID_PROFILE INTO VID_PROFILE FROM PROFILES 
    WHERE PASSWD=PASSWD_IN
    AND USERNAME=USERNAME_IN;
    RETURN VID_PROFILE;
    EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20001,'This combination of username and password does not exist');
  END ;
  
  FUNCTION INREGISTRARE
    (
      PASSWD_IN   IN VARCHAR2,
      USERNAME_IN IN VARCHAR2,
      EMAIL_IN    IN VARCHAR2
    )
    RETURN INTEGER
  IS
    PROFILE_IDD INTEGER;
  BEGIN
    INSERT
    INTO PROFILES
      (
        PASSWD,
        USERNAME,
        EMAIL
      )
      VALUES
      (
        PASSWD_IN,
        USERNAME_IN,
        EMAIL_IN
      );
    SELECT ID_PROFILE
    INTO PROFILE_IDD
    FROM PROFILES
    WHERE USERNAME=USERNAME_IN
    AND PASSWD    =PASSWD_IN;
    RETURN PROFILE_IDD;
    EXCEPTION
    WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20001,'Username already existing');
  END;
END ACCESS_UTILS;
/