DROP INDEX SORTARE_DATA;
DROP INDEX AFISARE_BADGE;
DROP INDEX LOGARE;
DROP INDEX CATEGORII_PREFERATE;
DROP INDEX INTREBARI_CATEGORII_PREFERATE;
DROP INDEX CAUTARE_TAG_URI;
DROP INDEX ID_QUESTION_QUESTIONS_KEYWORDS;
DROP INDEX RASPUNSURI;

CREATE INDEX LOGARE ON PROFILES
  (PASSWD,USERNAME
  );
/
EXPLAIN PLAN
SET STATEMENT_ID = 'log_in' FOR SELECT id_profile FROM profiles WHERE passwd='ewfwefwef' AND username='ewfwefwer';
SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'log_in','BASIC'));
/

CREATE INDEX CATEGORII_PREFERATE ON PROFILES_CATEGORIES
  (ID_PROFILE
  );
/

CREATE INDEX SORTARE_DATA ON QUESTIONS(TIME_POSTED);
/

CREATE INDEX INTREBARI_CATEGORII_PREFERATE ON QUESTIONS
  (
    ID_CATEGORY
  );
/
EXPLAIN PLAN
SET STATEMENT_ID = 'intreb_categ_pref' FOR SELECT * FROM
(SELECT  *
  FROM questions
  WHERE ID_CATEGORY IN
    (SELECT ID_CATEGORY FROM Profiles_categories WHERE ID_PROFILE=12
    )
  ORDER BY TIME_POSTED
)
WHERE ROWNUM BETWEEN 12 AND 15;
SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'intreb_categ_pref','BASIC'));
/

CREATE INDEX CAUTARE_TAG_URI ON QUESTIONS_TAGS
  (ID_TAG
  );
/
EXPLAIN PLAN
SET STATEMENT_ID = 'intreb_tag' FOR SELECT * FROM (SELECT ID_QUESTION FROM QUESTIONS_TAGS 
WHERE ID_TAG=(SELECT ID_TAG FROM TAGS 
                                   WHERE TAG_NAME='c++'))
WHERE ROWNUM BETWEEN 1 AND 30;
SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'intreb_tag','BASIC'));
/

CREATE INDEX ID_QUESTION_QUESTIONS_KEYWORDS ON QUESTIONS_KEYWORDS
  (
    ID_QUESTION
  );
/

CREATE INDEX AFISARE_BADGE ON PROFILES_BADGES(ID_PROFILE);
/
EXPLAIN PLAN
SET STATEMENT_ID = 'BADGE' FOR SELECT * FROM BADGES 
WHERE ID_BADGE IN  (SELECT ID_BADGE FROM PROFILES_BADGES
                        WHERE ID_PROFILE=4);
SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'BADGE','BASIC'));
/

CREATE INDEX RASPUNSURI ON ANSWERS(TIME_POSTED);
/

EXPLAIN PLAN
SET STATEMENT_ID = 'ANSWER' FOR SELECT * FROM ANSWERS 
WHERE ID_QUESTION=3234 ORDER BY TIME_POSTED;

SELECT PLAN_TABLE_OUTPUT
FROM TABLE(DBMS_XPLAN.DISPLAY(NULL, 'ANSWER','BASIC'));
/
