-----------------------------------bloc anonim de generare a profilelor

CREATE OR REPLACE PROCEDURE GENERATE_PROFILES (NUMBER_ROWS IN INTEGER) IS
  VLENGTH     INTEGER;
  VPASSWD     VARCHAR2(30);
  VUSERNAME   VARCHAR2(30);
  VFIRST_NAME VARCHAR2(30);
  VLAST_NAME  VARCHAR2(30);
  VAGE        INTEGER;
  EMST        VARCHAR2(30);
  EMF         VARCHAR2(30);
  VEMAIL      VARCHAR2(60);
  VCOUNTRY    VARCHAR2(60);
  VCITY       VARCHAR2(60);
  VIS_ADMIN   INTEGER;
  VIS_BANNED  INTEGER;
BEGIN
  FOR I IN 1..NUMBER_ROWS
  LOOP
    SELECT dbms_random.value(6,30) INTO VLENGTH FROM dual;
    SELECT dbms_random.string('U',VLENGTH) INTO VPASSWD FROM dual;
    SELECT dbms_random.value(6,30) INTO VLENGTH FROM dual;
    SELECT dbms_random.string('U',VLENGTH) INTO VUSERNAME FROM dual;
    SELECT dbms_random.value(6,30) INTO VLENGTH FROM dual;
    SELECT dbms_random.string('U',VLENGTH) INTO VFIRST_NAME FROM dual;
    SELECT dbms_random.value(6,30) INTO VLENGTH FROM dual;
    SELECT dbms_random.string('U',VLENGTH) INTO VLAST_NAME FROM dual;
    SELECT dbms_random.value(1,200) INTO VAGE FROM dual;
    SELECT dbms_random.value(1,30) INTO VLENGTH FROM dual;
    SELECT dbms_random.string('U',VLENGTH) INTO EMST FROM dual;
    SELECT dbms_random.value(1,25) INTO VLENGTH FROM dual;
    SELECT dbms_random.string('U',VLENGTH) INTO EMF FROM dual;
    VEMAIL:=EMST||'@'||EMF||'.com';
    SELECT dbms_random.value(1,60) INTO VLENGTH FROM dual;
    SELECT dbms_random.string('U',VLENGTH) INTO VCOUNTRY FROM dual;
    SELECT dbms_random.value(1,60) INTO VLENGTH FROM dual;
    SELECT dbms_random.string('U',VLENGTH) INTO VCITY FROM dual;
    SELECT dbms_random.value(0,1) INTO VIS_ADMIN FROM dual;
    SELECT dbms_random.value(0,1) INTO VIS_BANNED FROM dual;
    INSERT
    INTO PROFILES
      (
        PASSWD,
        USERNAME,
        FIRST_NAME,
        LAST_NAME,
        AGE,
        EMAIL,
        COUNTRY,
        CITY,
        IS_ADMIN,
        IS_BANNED
      )
      VALUES
      (
        VPASSWD,
        VUSERNAME,
        VFIRST_NAME,
        VLAST_NAME,
        VAGE,
        VEMAIL,
        VCOUNTRY,
        VCITY,
        VIS_ADMIN,
        VIS_BANNED
      );
  END LOOP;
  COMMIT;
END GENERATE_PROFILES;
/

--------------------------------------procedura de generare a intrebarilor----------------------

CREATE OR REPLACE PROCEDURE GENERATE_QUESTIONS (NUMBER_ROWS IN INTEGER) IS
  VLENGTH           INTEGER;
  VQUESTION_CONTENT VARCHAR2(500);
  VTIME_POSTED      DATE;
  VID_CATEGORY      INTEGER;
  VID_PROFILE       INTEGER;
  VNMB_VIEWS        INTEGER;
  NR_PROFILE        INTEGER;
  NMB_WORDS         INTEGER;
  NMBC              INTEGER;
BEGIN
  SELECT MAX(ROWNUM) INTO NR_PROFILE FROM PROFILES;
  FOR I IN 1..NUMBER_ROWS
  LOOP
    BEGIN
      SELECT dbms_random.value(1,500) INTO VLENGTH FROM dual;
      SELECT dbms_random.string('U',VLENGTH) INTO VQUESTION_CONTENT FROM dual;
      SELECT dbms_random.VALUE(20,30) INTO NMB_WORDS FROM dual;
      FOR INDX IN 1..NMB_WORDS LOOP
        SELECT dbms_random.value(1,500) INTO VLENGTH FROM dual;
        VQUESTION_CONTENT:=SUBSTR(VQUESTION_CONTENT,1,VLENGTH-1)||' '||SUBSTR(VQUESTION_CONTENT,VLENGTH+1,LENGTH(VQUESTION_CONTENT));
      END LOOP;      
      SELECT COUNT(*) INTO NMBC FROM CATEGORIES;
      SELECT dbms_random.value(1,NMBC) INTO VID_CATEGORY FROM dual;
      SELECT dbms_random.value(0,1000) INTO VLENGTH FROM dual;
      SELECT dbms_random.value(0,VLENGTH) INTO VNMB_VIEWS FROM dual;
      SELECT dbms_random.value(1,NR_PROFILE) INTO VID_PROFILE FROM dual;
      VTIME_POSTED:=TO_DATE(TRUNC(DBMS_RANDOM.value(TO_CHAR(DATE '1970-01-01 ','J'),TO_CHAR(SYSDATE,'J'))),'J');
      QUESTIONS_ANSWERS.POST_QUESTION(VID_PROFILE ,VQUESTION_CONTENT , VID_CATEGORY);       
    EXCEPTION
    WHEN OTHERS THEN
      EXIT;
    END;
  END LOOP;
  COMMIT;
END GENERATE_QUESTIONS;
/ 

-------------------------GENERARE RASPUNSURI--------------------------------
CREATE OR REPLACE PROCEDURE GENERATE_ANSWERS(NMB_QUEST IN INTEGER) IS
    VID_ANSWER INTEGER;
    VID_PROFILE INTEGER;
    VID_QUESTION INTEGER;
    VANSW_CONT VARCHAR2(500);
    VTIME_POSTED DATE;
    RAND1 INTEGER;
    RAND2 INTEGER;
    RAND3 INTEGER;
    NMB_WORDS INTEGER;
    L_ERRMSG VARCHAR2(4000);
BEGIN
  SELECT MAX(ID_PROFILE) INTO RAND1 FROM PROFILES;
  SELECT MAX(ID_QUESTION) INTO RAND2 FROM QUESTIONS;
  FOR INDX IN 1..NMB_QUEST LOOP
    BEGIN
      SELECT dbms_random.value(1,RAND1) INTO VID_PROFILE FROM dual;
      SELECT dbms_random.value(1,RAND2) INTO VID_QUESTION FROM dual;    
      SELECT dbms_random.value(1,500) INTO RAND3 FROM dual;
      SELECT dbms_random.string('U',RAND3) INTO VANSW_CONT FROM dual;
      SELECT dbms_random.VALUE(20,30) INTO NMB_WORDS FROM dual;
      FOR INDX IN 1..NMB_WORDS LOOP
        SELECT dbms_random.value(1,500) INTO RAND3 FROM dual;
        VANSW_CONT:=SUBSTR(VANSW_CONT,1,RAND3-1)||' '||SUBSTR(VANSW_CONT,RAND3+1,LENGTH(VANSW_CONT));
      END LOOP;
      QUESTIONS_ANSWERS.POST_ANSWER(VID_PROFILE ,VID_QUESTION,VANSW_CONT );
    EXCEPTION
    WHEN OTHERS THEN
    L_ERRMSG := SQLERRM;
    DBMS_OUTPUT.PUT_LINE(L_ERRMSG);
    EXIT;
    END;
  END LOOP;
  commit;
END GENERATE_ANSWERS;
/

BEGIN
  INSERT INTO CATEGORIES(NAME_CATEGORY) VALUES ('MATH');
  INSERT INTO CATEGORIES(NAME_CATEGORY) VALUES ('HISTORY');
  INSERT INTO CATEGORIES(NAME_CATEGORY) VALUES ('COMPUTER SCIENCE');
  INSERT INTO CATEGORIES(NAME_CATEGORY) VALUES ('LITERATURE');
  INSERT INTO CATEGORIES(NAME_CATEGORY) VALUES ('POLITICS');
  INSERT INTO CATEGORIES(NAME_CATEGORY) VALUES ('ARCHEOLOGY');
  INSERT INTO CATEGORIES(NAME_CATEGORY) VALUES ('BIOLOGY');
  INSERT INTO CATEGORIES(NAME_CATEGORY) VALUES ('CHEMISTRY');
  INSERT INTO CATEGORIES(NAME_CATEGORY) VALUES ('PHILOSOPHY');
  GENERATE_PROFILES(1000);
  GENERATE_QUESTIONS(100000);
  GENERATE_ANSWERS(50000);
END;
/

select * from profiles;
