DROP SEQUENCE SEQ_FOR_ANSWERS;
DROP SEQUENCE SEQ_FOR_PROFILES;
DROP SEQUENCE SEQ_FOR_CATEGORIES;
DROP SEQUENCE SEQ_FOR_QUESTIONS;
DROP SEQUENCE SEQ_FOR_TAGS;
DROP SEQUENCE SEQ_FOR_KEYWORDS;
DROP SEQUENCE SEQ_FOR_BADGES;

CREATE SEQUENCE SEQ_FOR_ANSWERS START WITH 1 INCREMENT BY 1 NOMAXVALUE;
 /
CREATE OR REPLACE TRIGGER ANSWERS_ID BEFORE
  INSERT ON ANSWERS FOR EACH ROW BEGIN
  SELECT SEQ_FOR_ANSWERS.NEXTVAL INTO :NEW.ID_ANSWER FROM DUAL;
END;
/
CREATE SEQUENCE SEQ_FOR_PROFILES START WITH 1 INCREMENT BY 1 NOMAXVALUE;
  /
CREATE OR REPLACE TRIGGER PROFILES_ID BEFORE
  INSERT ON PROFILES FOR EACH ROW BEGIN
  SELECT SEQ_FOR_PROFILES.NEXTVAL INTO :NEW.ID_PROFILE FROM DUAL;
END;
/
CREATE SEQUENCE SEQ_FOR_CATEGORIES START WITH 1 INCREMENT BY 1 NOMAXVALUE;
  /
CREATE OR REPLACE TRIGGER CATEGORIES_ID BEFORE
  INSERT ON CATEGORIES FOR EACH ROW BEGIN
  SELECT SEQ_FOR_CATEGORIES.NEXTVAL INTO :NEW.ID_CATEGORY FROM DUAL;
END;
/
CREATE SEQUENCE SEQ_FOR_QUESTIONS START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE OR REPLACE TRIGGER QUESTIONS_ID BEFORE
  INSERT ON QUESTIONS FOR EACH ROW BEGIN
  SELECT SEQ_FOR_QUESTIONS.NEXTVAL INTO :NEW.ID_QUESTION FROM DUAL;
END;
/
CREATE SEQUENCE SEQ_FOR_TAGS START WITH 1 INCREMENT BY 1 NOMAXVALUE;
  /
CREATE OR REPLACE TRIGGER TAGS_ID BEFORE
  INSERT ON TAGS FOR EACH ROW BEGIN
  SELECT SEQ_FOR_TAGS.NEXTVAL INTO :NEW.ID_TAG FROM DUAL;
END;
/
CREATE SEQUENCE SEQ_FOR_KEYWORDS START WITH 1 INCREMENT BY 1 NOMAXVALUE;
CREATE OR REPLACE TRIGGER KEYWORDS_ID BEFORE
  INSERT ON KEYWORDS FOR EACH ROW BEGIN
  SELECT SEQ_FOR_KEYWORDS.NEXTVAL INTO :NEW.ID_KEYWORD FROM DUAL;
END;
/
CREATE SEQUENCE SEQ_FOR_BADGES START WITH 1 INCREMENT BY 1 NOMAXVALUE;
  /
CREATE OR REPLACE TRIGGER BADGES_ID BEFORE
  INSERT ON BADGES FOR EACH ROW BEGIN
  SELECT SEQ_FOR_BADGES.NEXTVAL INTO :NEW.ID_BADGE FROM DUAL;
END;
/