SELECT * 
FROM ALL_OBJECTS
WHERE OWNER = 'DIMITRIE'
ORDER BY OBJECT_TYPE;

-- OR
SELECT OBJECT_NAME, OBJECT_TYPE
FROM ALL_OBJECTS
WHERE OWNER = 'DIMITRIE' AND OBJECT_TYPE IN ('VIEW', 'TRIGGER', 'FUNCTION', 'PROCEDURE', 'TYPE', 'OBJECT','INDEX')
ORDER BY OBJECT_TYPE;